server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: ERROR
    org.springframework.security.oauth2: INFO