server:
  port: 8090

logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: trace

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:9000