server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          product-client-cred:
            provider: spring
            client-id: product-client
            client-secret: secret
            authorization-grant-type: client_credentials
            client-name: product-client-cred
        provider:
          spring:
            issuer-uri: http://localhost:9000