server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          products-client-oidc:
            provider: spring
            client-id: product-client
            client-secret: product-secret
            authorization-grant-type: client_credentials
            redirect-uri: "http://127.0.0.1:9000/login/oauth2/code/{registrationId}"
            client-name: products-client-oidc
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9000