server:
  port: 8080

logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: trace

spring:
  security:
    oauth2:
      client:
        registration:
          products-reg-id:
            provider: spring
            client-id: product-client
            client-secret: secret
            authorization-grant-type: client_credentials
            #redirect-uri: "http://localhost:9000/login/oauth2/code/products-reg-id"
            client-name: products-reg-id
        provider:
          spring:
            issuer-uri: http://localhost:9000